version: '3.3'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TestDb123!"
    ports:
      - 1433:1433
    volumes:
      - database:/var/opt/mssql
      
volumes:
  database: